ietf/doc/urls.py
# Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
# All rights reserved. Contact: Pasi Eronen <pasi.eronen@nokia.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#
#  * Neither the name of the Nokia Corporation and/or its
#    subsidiary(-ies) nor the names of its contributors may be used
#    to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from django.conf.urls import patterns, url, include
from django.views.generic import RedirectView

from ietf.doc import views_search, views_draft, views_ballot
from ietf.doc import views_status_change
from ietf.doc import views_doc

urlpatterns = patterns('',
    (r'^/?$', views_search.search),
    url(r'^search/$', views_search.search, name="doc_search"),
    url(r'^in-last-call/$', views_search.drafts_in_last_call, name="drafts_in_last_call"),
    url(r'^ad/(?P<name>[A-Za-z0-9.-]+)/$', views_search.docs_for_ad, name="docs_for_ad"),
    (r'^ad2/(?P<name>[A-Za-z0-9.-]+)/$', RedirectView.as_view(url='/doc/ad/%(name)s/', permanent=True)),
    url(r'^rfc-status-changes/$', views_status_change.rfc_status_changes, name='rfc_status_changes'),
    url(r'^start-rfc-status-change/(?P<name>[A-Za-z0-9._+-]*)$', views_status_change.start_rfc_status_change, name='start_rfc_status_change'), 
    url(r'^iesg/(?P<last_call_only>[A-Za-z0-9.-]+/)?$', views_search.drafts_in_iesg_process, name="drafts_in_iesg_process"),
    url(r'^email-aliases/$', views_doc.email_aliases),

    url(r'^all/$', views_search.index_all_drafts, name="index_all_drafts"),
    url(r'^active/$', views_search.index_active_drafts, name="index_active_drafts"),
    url(r'^select2search/(?P<model_name>(document|docalias))/(?P<doc_type>draft)/$', views_search.ajax_select2_search_docs, name="ajax_select2_search_docs"),

    url(r'^(?P<name>[A-Za-z0-9._+-]+)/(?:(?P<rev>[0-9-]+)/)?$', views_doc.document_main, name="doc_view"),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/history/$', views_doc.document_history, name="doc_history"),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/writeup/$', views_doc.document_writeup, name="doc_writeup"),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/shepherdwriteup/$', views_doc.document_shepherd_writeup, name="doc_shepherd_writeup"),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/references/$', views_doc.document_references, name="doc_references"),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/referencedby/$', views_doc.document_referenced_by, name="doc_referenced_by"),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/ballot/(?P<ballot_id>[0-9]+)/position/$', views_ballot.edit_position),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/ballot/(?P<ballot_id>[0-9]+)/emailposition/$', views_ballot.send_ballot_comment, name='doc_send_ballot_comment'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/ballot/(?P<ballot_id>[0-9]+)/$', views_doc.document_ballot, name="doc_ballot"),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/ballot/$', views_doc.document_ballot, name="doc_ballot"),
    (r'^(?P<name>[A-Za-z0-9._+-]+)/doc.json$', views_doc.document_json),
    (r'^(?P<name>[A-Za-z0-9._+-]+)/ballotpopup/(?P<ballot_id>[0-9]+)/$', views_doc.ballot_popup),

    url(r'^(?P<name>[A-Za-z0-9._+-]+)/email-aliases/$', views_doc.email_aliases),

    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/state/$', views_draft.change_state, name='doc_change_state'), # IESG state
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/state/(?P<state_type>iana-action|iana-review)/$', views_draft.change_iana_state, name='doc_change_iana_state'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/info/$', views_draft.edit_info, name='doc_edit_info'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/requestresurrect/$', views_draft.request_resurrect, name='doc_request_resurrect'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/submit-to-iesg/$', views_draft.to_iesg, name='doc_to_iesg'), 
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/resurrect/$', views_draft.resurrect, name='doc_resurrect'),                       
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/addcomment/$', views_doc.add_comment, name='doc_add_comment'),
    url(r'^ajax/internet_draft/?$', views_draft.doc_ajax_internet_draft, name="doc_ajax_internet_draft"),

    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/stream/$', views_draft.change_stream, name='doc_change_stream'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/replaces/$', views_draft.replaces, name='doc_change_replaces'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/notify/$', views_doc.edit_notify, name='doc_change_notify'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/status/$', views_draft.change_intention, name='doc_change_intended_status'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/telechat/$', views_doc.telechat_date, name='doc_change_telechat_date'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/iesgnote/$', views_draft.edit_iesg_note, name='doc_change_iesg_note'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/ad/$', views_draft.edit_ad, name='doc_change_ad'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/consensus/$', views_draft.edit_consensus, name='doc_edit_consensus'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/shepherd/$', views_draft.edit_shepherd, name='doc_edit_shepherd'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/shepherdemail/$', views_draft.change_shepherd_email, name='doc_change_shepherd_email'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/shepherdwriteup/$', views_draft.edit_shepherd_writeup, name='doc_edit_shepherd_writeup'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/requestpublication/$', views_draft.request_publication, name='doc_request_publication'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/adopt/$', views_draft.adopt_draft, name='doc_adopt_draft'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/state/(?P<state_type>draft-stream-[a-z]+)/$', views_draft.change_stream_state, name='doc_change_stream_state'),

    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/clearballot/$', views_ballot.clear_ballot, name='doc_clear_ballot'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/deferballot/$', views_ballot.defer_ballot, name='doc_defer_ballot'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/undeferballot/$', views_ballot.undefer_ballot, name='doc_undefer_ballot'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/lastcalltext/$', views_ballot.lastcalltext, name='doc_ballot_lastcall'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/ballotwriteupnotes/$', views_ballot.ballot_writeupnotes, name='doc_ballot_writeupnotes'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/approvaltext/$', views_ballot.ballot_approvaltext, name='doc_ballot_approvaltext'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/approveballot/$', views_ballot.approve_ballot, name='doc_approve_ballot'),
    url(r'^(?P<name>[A-Za-z0-9._+-]+)/edit/makelastcall/$', views_ballot.make_last_call, name='doc_make_last_call'),

    url(r'^help/state/(?P<type>[\w-]+)/$', 'ietf.doc.views_help.state_help', name="state_help"),
    url(r'^help/relationships/$', 'ietf.doc.views_help.relationship_help', name="relationship_help"),
    url(r'^help/relationships/(?P<subset>\w+)/$', 'ietf.doc.views_help.relationship_help', name="relationship_subset_help"),

    (r'^(?P<name>charter-[A-Za-z0-9._+-]+)/', include('ietf.doc.urls_charter')),
    (r'^(?P<name>[A-Za-z0-9._+-]+)/conflict-review/', include('ietf.doc.urls_conflict_review')),
    (r'^(?P<name>[A-Za-z0-9._+-]+)/status-change/', include('ietf.doc.urls_status_change')),
    (r'^(?P<name>[A-Za-z0-9._+-]+)/material/', include('ietf.doc.urls_material')),
)

ietf/docs/urls.py
# Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
# All rights reserved. Contact: Pasi Eronen <pasi.eronen@nokia.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#
#  * Neither the name of the Nokia Corporation and/or its
#    subsidiary(-ies) nor the names of its contributors may be used
#    to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from django.conf.urls.defaults import patterns
from ietf.docs import views

urlpatterns = patterns('',
    (r'^test.html$', views.test)
)

ietf/submit/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('ietf.submit.views',
    url(r'^$', 'upload_submission', name='submit_upload_submission'),
    url(r'^status/$', 'search_submission', name='submit_search_submission'),
    url(r'^status/(?P<submission_id>\d+)/$', 'submission_status', name='submit_submission_status'),
    url(r'^status/(?P<submission_id>\d+)/edit/$', 'edit_submission', name='submit_edit_submission'),
    url(r'^status/(?P<submission_id>\d+)/confirm/(?P<auth_token>[a-f\d]+)/$', 'confirm_submission', name='submit_confirm_submission'),
    url(r'^status/(?P<submission_id>\d+)/(?P<access_token>[a-f\d]*)/$', 'submission_status', name='submit_submission_status_by_hash'),
    url(r'^status/(?P<submission_id>\d+)/(?P<access_token>[a-f\d]+)/edit/$', 'edit_submission', name='submit_edit_submission_by_hash'),
    url(r'^note-well/$', 'note_well', name='submit_note_well'),
    url(r'^tool-instructions/$', 'tool_instructions', name='submit_tool_instructions'),

    url(r'^approvals/$', 'approvals', name='submit_approvals'),
    url(r'^approvals/addpreapproval/$', 'add_preapproval', name='submit_add_preapproval'),
    url(r'^approvals/cancelpreapproval/(?P<preapproval_id>[a-f\d]+)/$', 'cancel_preapproval', name='submit_cancel_preapproval'),
)

ietf/urls.py
# Copyright The IETF Trust 2007, 2009, All Rights Reserved

from django.conf.urls import patterns, include
from django.contrib import admin
from django.views.generic import TemplateView

from ietf.liaisons.sitemaps import LiaisonMap
from ietf.ipr.sitemaps import IPRMap
from ietf import api

from django.conf import settings

admin.autodiscover()
api.autodiscover()

# sometimes, this code gets called more than once, which is an
# that seems impossible to work around.
try:
    admin.site.disable_action('delete_selected')
except KeyError:
    pass

sitemaps = {
    'liaison': LiaisonMap,
    'ipr': IPRMap,
}

urlpatterns = patterns('',
    (r'^$', 'ietf.doc.views_search.frontpage'),
    (r'^accounts/', include('ietf.ietfauth.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^ann/', include('ietf.nomcom.redirect_ann_urls')),
    (r'^community/', include('ietf.community.urls')),
    (r'^accounts/settings/', include('ietf.cookies.urls')),
    (r'^doc/', include('ietf.doc.urls')),
    (r'^drafts/', include('ietf.doc.redirect_drafts_urls')),
    (r'^feed/', include('ietf.feed_urls')),
    (r'^group/', include('ietf.group.urls')),
    (r'^help/', include('ietf.help.urls')),
    (r'^idtracker/', include('ietf.doc.redirect_idtracker_urls')),
    (r'^iesg/', include('ietf.iesg.urls')),
    (r'^ipr/', include('ietf.ipr.urls')),
    (r'^liaison/', include('ietf.liaisons.urls')),
    (r'^list/', include('ietf.mailinglists.urls')),
    (r'^meeting/', include('ietf.meeting.urls')),
    (r'^nomcom/', include('ietf.nomcom.urls')),
    (r'^person/', include('ietf.person.urls')),
    (r'^release/', include('ietf.release.urls')),
    (r'^secr/', include('ietf.secr.urls')),
    (r'^sitemap-(?P<section>.+).xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.index', { 'sitemaps': sitemaps}),
    (r'^submit/', include('ietf.submit.urls')),
    (r'^sync/', include('ietf.sync.urls')),
    (r'^stream/', include('ietf.group.urls_stream')),
    (r'^templates/', include('ietf.dbtemplate.urls')),
    (r'^(?P<group_type>(wg|rg))/', include('ietf.group.urls_info')),

    # Redirects
    (r'^(?P<path>public)/', include('ietf.redirects.urls')),

    # Google webmaster tools verification url
    (r'^googlea30ad1dacffb5e5b.html', TemplateView.as_view(template_name='googlea30ad1dacffb5e5b.html')),
)

# Endpoints for Tastypie's REST API
urlpatterns += patterns('',
    (r'^api/v1/?$', api.top_level),
)
for n,a in api._api_list:
    urlpatterns += patterns('',
        (r'^api/v1/', include(a.urls)),
    )

if settings.SERVER_MODE in ('development', 'test'):
    urlpatterns += patterns('',
        (r'^(?P<path>(?:images|css|js|test|static|fonts|other)/.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^(?P<path>admin/(?:img|css|js)/.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^(?P<path>secretariat/(img|css|js)/.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^(?P<path>robots\.txt)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT+"dev/"}),
        (r'^_test500/$', lambda x: None),
        (r'^environment/$', 'ietf.help.views.environment'),
	)

ietf/doc/forms.py
import datetime

from django import forms

from ietf.iesg.models import TelechatDate

class TelechatForm(forms.Form):
    telechat_date = forms.TypedChoiceField(coerce=lambda x: datetime.datetime.strptime(x, '%Y-%m-%d').date(), empty_value=None, required=False)
    returning_item = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)

        dates = [d.date for d in TelechatDate.objects.active().order_by('date')]
        init = kwargs['initial'].get("telechat_date")
        if init and init not in dates:
            dates.insert(0, init)

        self.fields['telechat_date'].choices = [("", "(not on agenda)")] + [(d, d.strftime("%Y-%m-%d")) for d in dates]

from ietf.person.models import Person

class AdForm(forms.Form):
    ad = forms.ModelChoiceField(Person.objects.filter(role__name="ad", role__group__state="active", role__group__type='area').order_by('name'),
                                label="Shepherding AD", empty_label="(None)", required=True)

    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)

        # if previous AD is now ex-AD, append that person to the list
        ad_pk = self.initial.get('ad')
        choices = self.fields['ad'].choices
        if ad_pk and ad_pk not in [pk for pk, name in choices]:
            self.fields['ad'].choices = list(choices) + [("", "-------"), (ad_pk, Person.objects.get(pk=ad_pk).plain_name())]

class NotifyForm(forms.Form):
    notify = forms.CharField(max_length=255, help_text="List of email addresses to receive state notifications, separated by comma.", label="Notification list", required=False)

    def clean_notify(self):
        addrspecs = [x.strip() for x in self.cleaned_data["notify"].split(',')]
        return ', '.join(addrspecs)

ietf/templates/doc/conflict_review/approve.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}Approve {{ review.canonical_name }}{% endblock %}

{% block content %}
  <h1>Approve {{ review.canonical_name }}</h1>

  {% bootstrap_messages %}

  <form role="form" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button type="submit" class="btn btn-warning">Send announcement & close ballot</button>
      <a class="btn btn-default pull-right" href="{% url "doc_view" name=review.name %}">Back</a>
    {% endbuttons %}
  </form>

{% endblock %}

ietf/templates/doc/conflict_review/change_ad.html
{% extends "base.html" %}

{% block morecss %}
.warning {
  font-weight: bold;
  color: #a00;
}
{% endblock %}

{% block title %}
Change the shepherding AD for the conflict review of {{ conflictdoc.canonical_name }}-{{ conflictdoc.rev }}
{% endblock %}

{% block content %}
<h1>Change the shepherding AD for the conflict review of {{ conflictdoc.canonical_name }}-{{ conflictdoc.rev }}</h1>

<form class="edit-info" action="" enctype="multipart/form-data" method="POST">
  <table>
    {% for field in form.visible_fields %}
    <tr>
      <th>{{ field.label_tag }}:</th>
      <td>
        {{ field }}
	{% if field.help_text %}<div class="help">{{ field.help_text }}</div>{% endif %}
        {{ field.errors }}
      </td>
    </tr>
    {% endfor %}
    <tr>
      <td></td>
      <td class="actions">
        <a href="{% url doc_view name=review.canonical_name %}">Back</a>
        <input type="submit" value="Submit"/>
      </td>
    </tr>
  </table>
</form>

{% endblock %}

ietf/templates/doc/conflict_review/change_state.html
{% extends "base.html" %}

{% block title %}Change State: {{doc.title}}{% endblock %}

{% block morecss %}
form.change-state select {
  width: 22em;
}

#id_message, #id_comment {
  width: 40em;
}

form.change-state .actions {
  text-align: right;
  padding-top: 10px;
}
{% endblock %}

{% block content %}
<h1>Change State: {{doc.title}}</h1>

<p class="helptext">For help on the states, see the <a href="{% url state_help type="conflict-review" %}">state table</a>.</p>

<form class="change-state" action="" method="post">
  <table>
    {% for field in form.visible_fields %}
    <tr>
      <th>{{ field.label_tag }}:</th>
      <td>{{ field }}
      {% if field.help_text %}<div class="help">{{ field.help_text }}</div>{% endif %}

      {{ field.errors }}
      </td>
    </tr>
    {% endfor %}
    <tr>
      <td colspan="2" class="actions">
        <a href="{% url doc_view name=doc.name %}">Back</a>
        <input type="submit" value="Submit"/>
      </td>
    </tr>
  </table>
</form>

{% endblock %}

ietf/templates/doc/conflict_review/notify.html
{% extends "base.html" %}

{% block morecss %}
form.edit-info #id_notify {
  width: 600px;
}
.warning {
  font-weight: bold;
  color: #a00;
}
{% endblock %}

{% block title %}
Edit notification addresses for the conflict review of {{ conflictdoc.canonical_name }}-{{ conflictdoc.rev }}
{% endblock %}

{% block content %}
<h1>Edit notification addresses for the conflict review of {{ conflictdoc.canonical_name }}-{{ conflictdoc.rev }}</h1>

<form class="edit-info" action="" enctype="multipart/form-data" method="POST">
  <table>
    {% for field in form.visible_fields %}
    <tr>
      <th>{{ field.label_tag }}:</th>
      <td>
        {{ field }}
	{% if field.help_text %}<div class="help">{{ field.help_text }}</div>{% endif %}
        {{ field.errors }}
      </td>
    </tr>
    {% endfor %}
    <tr>
      <td></td>
      <td class="actions">
        <a href="{% url doc_view name=review.canonical_name %}">Back</a>
        <input type="submit" value="Submit"/>
      </td>
    </tr>
  </table>
</form>

{% endblock %}

ietf/templates/doc/conflict_review/start.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% load ietf_filters %}

{% block title %}Begin IETF conflict review for {{doc_to_review.canonical_name}}-{{doc_to_review.rev}}{% endblock %}

{% block content %}
  <h1>Begin IETF conflict review<br><small>{{doc_to_review.canonical_name}}-{{doc_to_review.rev}}</small></h1>

  {% bootstrap_messages %}

  {% if user|has_role:"Secretariat" %}
    <p><a class="btn btn-info" href="{% url "state_help" type="conflict-review" %}">Help on states</a></p>
  {% endif %}

  <form role="form" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button type="submit" class="btn btn-primary">Submit</button>
      <a class="btn btn-default pull-right" href="{% url "doc_view" name=doc_to_review.name %}">Back</a>
    {% endbuttons %}
  </form>

{% endblock %}

ietf/templates/doc/conflict_review/submit.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}
  Edit conflict review for {{ conflictdoc.canonical_name }}-{{ conflictdoc.rev }}
{% endblock %}

{% block content %}
  <h1>Edit conflict review<br><small>{{ conflictdoc.canonical_name }}-{{ conflictdoc.rev }}</small></h1>

  {% bootstrap_messages %}

  <p class="alert alert-info">The text will be submitted as <strong>{{ review.canonical_name }}-{{ next_rev }}</strong></p>

  <form role="form" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button type="submit" class="btn btn-primary" name="submit_response">Submit</button>
      <button type="submit" class="btn btn-warning" name="reset_text">Reset to template text</button>
      <a class="btn btn-default pull-right" href="{% url "doc_view" name=review.canonical_name %}">Back</a>
    {% endbuttons %}

  </form>

{% endblock %}