ietf/group/urls.py
# Copyright The IETF Trust 2007, All Rights Reserved

from django.conf.urls import patterns

urlpatterns = patterns('',
    (r'^groupmenu.json', 'ietf.group.ajax.group_menu_data', None, "group_menu_data"),
    (r'^(?P<acronym>[a-z0-9]+).json$', 'ietf.group.ajax.group_json'),
    (r'^chartering/$', 'ietf.group.info.chartering_groups'),
    (r'^chartering/create/(?P<group_type>(wg|rg))/$', 'ietf.group.edit.edit', {'action': "charter"}, "group_create"),
    (r'^concluded/$', 'ietf.group.info.concluded_groups'),
    (r'^email-aliases/$', 'ietf.group.info.email_aliases'),
    # FIXME: the things below are duplicated in urls_info.py while we
    # figure out whether to serve everything from /group/<acronym>,
    # need to unify these at some point
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/$', 'ietf.group.info.group_home', None, "group_home"),
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/documents/$', 'ietf.group.info.group_documents', None, "group_docs"),
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/charter/$', 'ietf.group.info.group_about', None, 'group_charter'),
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/history/$', 'ietf.group.info.history'),
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/deps/dot/$', 'ietf.group.info.dependencies_dot'),
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/deps/pdf/$', 'ietf.group.info.dependencies_pdf'),
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/init-charter/', 'ietf.group.edit.submit_initial_charter'),
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/edit/$', 'ietf.group.edit.edit', {'action': "edit"}, "group_edit"),
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/conclude/$', 'ietf.group.edit.conclude'),
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/milestones/$', 'ietf.group.milestones.edit_milestones', {'milestone_set': "current"}, "group_edit_milestones"),
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/milestones/charter/$', 'ietf.group.milestones.edit_milestones', {'milestone_set': "charter"}, "group_edit_charter_milestones"),
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/milestones/charter/reset/$', 'ietf.group.milestones.reset_charter_milestones', None, "group_reset_charter_milestones"),
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/workflow/$', 'ietf.group.edit.customize_workflow'),

    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/about/(?P<group_type>.)?$', 'ietf.group.info.group_about', None, 'group_about'),
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/materials/$', 'ietf.group.info.materials', None, "group_materials"),
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/materials/new/$', 'ietf.doc.views_material.choose_material_type'),
    (r'^(?P<acronym>[a-zA-Z0-9-._]+)/materials/new/(?P<doc_type>[\w-]+)/$', 'ietf.doc.views_material.edit_material', { 'action': "new" }, "group_new_material"),
    (r'^(?P<acronym>[A-Za-z0-9._+-]+)/email-aliases/$', 'ietf.group.info.email_aliases'),
)

ietf/person/urls.py
from django.conf.urls import patterns
from ietf.person import ajax

urlpatterns = patterns('',
        (r'^search/(?P<model_name>(person|email))/$', "ietf.person.views.ajax_select2_search", None, 'ajax_select2_search_person_email'),
        (r'^(?P<personid>[a-z0-9]+).json$', ajax.person_json),
)

ietf/secr/urls.py
from django.conf.urls import patterns, url, include
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='main.html'), name="home"),
    (r'^announcement/', include('ietf.secr.announcement.urls')),
    (r'^areas/', include('ietf.secr.areas.urls')),
    (r'^console/', include('ietf.secr.console.urls')),
    (r'^drafts/', include('ietf.secr.drafts.urls')),
    (r'^groups/', include('ietf.secr.groups.urls')),
    (r'^meetings/', include('ietf.secr.meetings.urls')),
    (r'^proceedings/', include('ietf.secr.proceedings.urls')),
    (r'^roles/', include('ietf.secr.roles.urls')),
    (r'^rolodex/', include('ietf.secr.rolodex.urls')),
    (r'^sreq/', include('ietf.secr.sreq.urls')),
    (r'^telechat/', include('ietf.secr.telechat.urls')),
)

ietf/urls.py
# Copyright The IETF Trust 2007, 2009, All Rights Reserved

from django.conf.urls import patterns, include
from django.contrib import admin
from django.views.generic import TemplateView

from ietf.liaisons.sitemaps import LiaisonMap
from ietf.ipr.sitemaps import IPRMap
from ietf import api

from django.conf import settings

admin.autodiscover()
api.autodiscover()

# sometimes, this code gets called more than once, which is an
# that seems impossible to work around.
try:
    admin.site.disable_action('delete_selected')
except KeyError:
    pass

sitemaps = {
    'liaison': LiaisonMap,
    'ipr': IPRMap,
}

urlpatterns = patterns('',
    (r'^$', 'ietf.doc.views_search.frontpage'),
    (r'^accounts/', include('ietf.ietfauth.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^ann/', include('ietf.nomcom.redirect_ann_urls')),
    (r'^community/', include('ietf.community.urls')),
    (r'^accounts/settings/', include('ietf.cookies.urls')),
    (r'^doc/', include('ietf.doc.urls')),
    (r'^drafts/', include('ietf.doc.redirect_drafts_urls')),
    (r'^feed/', include('ietf.feed_urls')),
    (r'^group/', include('ietf.group.urls')),
    (r'^help/', include('ietf.help.urls')),
    (r'^idtracker/', include('ietf.doc.redirect_idtracker_urls')),
    (r'^iesg/', include('ietf.iesg.urls')),
    (r'^ipr/', include('ietf.ipr.urls')),
    (r'^liaison/', include('ietf.liaisons.urls')),
    (r'^list/', include('ietf.mailinglists.urls')),
    (r'^meeting/', include('ietf.meeting.urls')),
    (r'^nomcom/', include('ietf.nomcom.urls')),
    (r'^person/', include('ietf.person.urls')),
    (r'^release/', include('ietf.release.urls')),
    (r'^secr/', include('ietf.secr.urls')),
    (r'^sitemap-(?P<section>.+).xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.index', { 'sitemaps': sitemaps}),
    (r'^submit/', include('ietf.submit.urls')),
    (r'^sync/', include('ietf.sync.urls')),
    (r'^stream/', include('ietf.group.urls_stream')),
    (r'^templates/', include('ietf.dbtemplate.urls')),
    (r'^(?P<group_type>(wg|rg))/', include('ietf.group.urls_info')),

    # Redirects
    (r'^(?P<path>public)/', include('ietf.redirects.urls')),

    # Google webmaster tools verification url
    (r'^googlea30ad1dacffb5e5b.html', TemplateView.as_view(template_name='googlea30ad1dacffb5e5b.html')),
)

# Endpoints for Tastypie's REST API
urlpatterns += patterns('',
    (r'^api/v1/?$', api.top_level),
)
for n,a in api._api_list:
    urlpatterns += patterns('',
        (r'^api/v1/', include(a.urls)),
    )

if settings.SERVER_MODE in ('development', 'test'):
    urlpatterns += patterns('',
        (r'^(?P<path>(?:images|css|js|test|static|fonts|other)/.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^(?P<path>admin/(?:img|css|js)/.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^(?P<path>secretariat/(img|css|js)/.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^(?P<path>robots\.txt)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT+"dev/"}),
        (r'^_test500/$', lambda x: None),
        (r'^environment/$', 'ietf.help.views.environment'),
	)

ietf/group/models.py
# Copyright The IETF Trust 2007, All Rights Reserved

import datetime
from urlparse import urljoin

from django.db import models

from ietf.group.colors import fg_group_colors, bg_group_colors
from ietf.name.models import GroupStateName, GroupTypeName, DocTagName, GroupMilestoneStateName, RoleName
from ietf.person.models import Email, Person

import debug                            # pyflakes:ignore

class GroupInfo(models.Model):
    time = models.DateTimeField(default=datetime.datetime.now)
    name = models.CharField(max_length=80)
    state = models.ForeignKey(GroupStateName, null=True)
    type = models.ForeignKey(GroupTypeName, null=True)
    parent = models.ForeignKey('Group', blank=True, null=True)
    description = models.TextField(blank=True)
    list_email = models.CharField(max_length=64, blank=True)
    list_subscribe = models.CharField(max_length=255, blank=True)
    list_archive = models.CharField(max_length=255, blank=True)
    comments = models.TextField(blank=True)

    unused_states = models.ManyToManyField('doc.State', help_text="Document states that have been disabled for the group.", blank=True)
    unused_tags = models.ManyToManyField(DocTagName, help_text="Document tags that have been disabled for the group.", blank=True)

    def __unicode__(self):
        return self.name

    def name_with_acronym(self):
        res = self.name
        if self.type_id in ("wg", "rg", "area"):
            res += " %s (%s)" % (self.type, self.acronym)
        return res

    def ad_role(self):
        return self.role_set.filter(name='ad').first()

    @property
    def features(self):
        if not hasattr(self, "features_cache"):
            from ietf.group.features import GroupFeatures
            self.features_cache = GroupFeatures(self)
        return self.features_cache

    def about_url(self):
        # bridge gap between group-type prefixed URLs and /group/ ones
        from django.core.urlresolvers import reverse as urlreverse
        kwargs = { 'acronym': self.acronym }
        if self.type_id in ("wg", "rg"):
            kwargs["group_type"] = self.type_id
        return urlreverse(self.features.about_page, kwargs=kwargs)

    class Meta:
        abstract = True

class GroupManager(models.Manager):
    def active_wgs(self):
        return self.get_queryset().filter(type='wg', state__in=('bof','proposed','active'))

class Group(GroupInfo):
    objects = GroupManager()

    acronym = models.SlugField(max_length=40, unique=True, db_index=True)
    charter = models.OneToOneField('doc.Document', related_name='chartered_group', blank=True, null=True)

    def latest_event(self, *args, **filter_args):
        """Get latest event of optional Python type and with filter
        arguments, e.g. g.latest_event(type="xyz") returns a GroupEvent
        while g.latest_event(ChangeStateGroupEvent, type="xyz") returns a
        ChangeStateGroupEvent event."""
        model = args[0] if args else GroupEvent
        e = model.objects.filter(group=self).filter(**filter_args).order_by('-time', '-id')[:1]
        return e[0] if e else None

    def has_role(self, user, role_names):
        if isinstance(role_names, str) or isinstance(role_names, unicode):
            role_names = [role_names]
        return user.is_authenticated() and self.role_set.filter(name__in=role_names, person__user=user).exists()

    def is_bof(self):
        return (self.state.slug in ["bof", "bof-conc"])

    def get_chair(self):
        chair = self.role_set.filter(name__slug='chair')[:1]
        return chair and chair[0] or None

    # these are copied to Group because it is still proxied.
    @property
    def upcase_acronym(self):
        return self.acronym.upper()

    @property
    def fg_color(self):
        return fg_group_colors[self.upcase_acronym]

    @property
    def bg_color(self):
        return bg_group_colors[self.upcase_acronym]

    def json_url(self):
        return "/group/%s.json" % (self.acronym,)

    def json_dict(self, host_scheme):
        group1= dict()
        group1['href'] = urljoin(host_scheme, self.json_url())
        group1['acronym'] = self.acronym
        group1['name']    = self.name
        group1['state']   = self.state.slug
        group1['type']    = self.type.slug
        if self.parent is not None:
            group1['parent_href']  = urljoin(host_scheme, self.parent.json_url())
        # uncomment when people URL handle is created
        try:
            if self.ad_role() is not None:
                group1['ad_href']      = urljoin(host_scheme, self.ad_role().person.json_url())
        except Person.DoesNotExist:
            pass
        group1['list_email'] = self.list_email
        group1['list_subscribe'] = self.list_subscribe
        group1['list_archive'] = self.list_archive
        group1['comments']     = self.comments
        return group1

    def has_tools_page(self):
        return self.type_id in ['wg', ] and self.state_id in ['active', 'dormant', 'replaced', 'conclude']

class GroupHistory(GroupInfo):
    group = models.ForeignKey(Group, related_name='history_set')
    acronym = models.CharField(max_length=40)

    class Meta:
        verbose_name_plural="group histories"

class GroupURL(models.Model):
    group = models.ForeignKey(Group)
    name = models.CharField(max_length=255)
    url = models.URLField()

    def __unicode__(self):
        return u"%s (%s)" % (self.url, self.name)

class GroupMilestoneInfo(models.Model):
    group = models.ForeignKey(Group)
    # a group has two sets of milestones, current milestones
    # (active/under review/deleted) and charter milestones (active
    # during a charter/recharter event), events for charter milestones
    # are stored on the charter document
    state = models.ForeignKey(GroupMilestoneStateName)
    desc = models.CharField(verbose_name="Description", max_length=500)
    due = models.DateField()
    resolved = models.CharField(max_length=50, blank=True, help_text="Explanation of why milestone is resolved (usually \"Done\"), or empty if still due.")

    docs = models.ManyToManyField('doc.Document', blank=True)

    def __unicode__(self):
        return self.desc[:20] + "..."
    class Meta:
        abstract = True
        ordering = ['due', 'id']

class GroupMilestone(GroupMilestoneInfo):
    time = models.DateTimeField(auto_now=True)

class GroupMilestoneHistory(GroupMilestoneInfo):
    time = models.DateTimeField()
    milestone = models.ForeignKey(GroupMilestone, related_name="history_set")

class GroupStateTransitions(models.Model):
    """Captures that a group has overriden the default available
    document state transitions for a certain state."""
    group = models.ForeignKey(Group)
    state = models.ForeignKey('doc.State', help_text="State for which the next states should be overridden")
    next_states = models.ManyToManyField('doc.State', related_name='previous_groupstatetransitions_states')

    def __unicode__(self):
        return u'%s "%s" -> %s' % (self.group.acronym, self.state.name, [s.name for s in self.next_states.all()])

GROUP_EVENT_CHOICES = [
    ("changed_state", "Changed state"),
    ("added_comment", "Added comment"),
    ("info_changed", "Changed metadata"),
    ("requested_close", "Requested closing group"),
    ("changed_milestone", "Changed milestone"),
    ("sent_notification", "Sent notification")
    ]

class GroupEvent(models.Model):
    """An occurrence for a group, used for tracking who, when and what."""
    group = models.ForeignKey(Group)
    time = models.DateTimeField(default=datetime.datetime.now, help_text="When the event happened")
    type = models.CharField(max_length=50, choices=GROUP_EVENT_CHOICES)
    by = models.ForeignKey(Person)
    desc = models.TextField()

    def __unicode__(self):
        return u"%s %s at %s" % (self.by.plain_name(), self.get_type_display().lower(), self.time)

    class Meta:
        ordering = ['-time', 'id']

class ChangeStateGroupEvent(GroupEvent):
    state = models.ForeignKey(GroupStateName)

class MilestoneGroupEvent(GroupEvent):
    milestone = models.ForeignKey(GroupMilestone)

class Role(models.Model):
    name = models.ForeignKey(RoleName)
    group = models.ForeignKey(Group)
    person = models.ForeignKey(Person)
    email = models.ForeignKey(Email, help_text="Email address used by person for this role.")
    def __unicode__(self):
        return u"%s is %s in %s" % (self.person.plain_name(), self.name.name, self.group.acronym or self.group.name)

    def formatted_email(self):
        return u'"%s" <%s>' % (self.person.plain_name(), self.email.address)

class RoleHistory(models.Model):
    # RoleHistory doesn't have a time field as it's not supposed to be
    # used on its own - there should always be a GroupHistory
    # accompanying a change in roles, so lookup the appropriate
    # GroupHistory instead
    name = models.ForeignKey(RoleName)
    group = models.ForeignKey(GroupHistory)
    person = models.ForeignKey(Person)
    email = models.ForeignKey(Email, help_text="Email address used by person for this role.")
    def __unicode__(self):
        return u"%s is %s in %s" % (self.person.plain_name(), self.name.name, self.group.acronym)

    class Meta:
        verbose_name_plural = "role histories"

ietf/secr/console/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

from ietf.doc.models import DocEvent
from ietf.ietfauth.utils import role_required

@role_required('Secretariat')
def main(request):
    '''
    Main view for the Console
    '''

    latest_docevent = DocEvent.objects.all().order_by('-time')[0]
    
    return render_to_response('console/main.html', {
        'latest_docevent': latest_docevent},
        RequestContext(request, {}),
    )

ietf/secr/templates/groups/add.html
{% extends "base_site.html" %}

{% block title %}Groups - Add{% endblock %}

{% block extrahead %}{{ block.super }}
  <script type="text/javascript" src="{{ SECR_STATIC_URL }}js/utils.js"></script>
{% endblock %}

{% block breadcrumbs %}{{ block.super }} 
  &raquo; <a href="../">Groups</a>
  &raquo; Add 
{% endblock %}

{% block content %}

<div class="module group-container">
    <h2>Groups - Add</h2>
    <form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
      <table id="groups-table" class="full-width amstable">
        <col width="150">
        {{ form.as_table }}
      </table>

      {% include "includes/awp_add_form.html" %}

      {% include "includes/buttons_save_cancel.html" %}

    </form>
</div> <!-- module -->

{% endblock %}

ietf/secr/templates/groups/charter.html
{% extends "base_site.html" %}

{% block title %}Groups - Charter{% endblock %}

{% block extrahead %}{{ block.super }}
  <script type="text/javascript" src="{{ SECR_STATIC_URL }}js/utils.js"></script>
{% endblock %}

{% block breadcrumbs %}{{ block.super }} 
  &raquo; <a href="../../">Groups</a>
  &raquo; <a href="../">{{ group.acronym }}</a>
  &raquo; Charter
{% endblock %}

{% block content %}

<div class="module group-container">
    <h2>Groups - Charter</h2>
    <pre>
    {% if charter_txt %}{{ charter_text }}{% else %}Charter not found.{% endif %}
    </pre>
</div> <!-- module -->

{% endblock %}

ietf/secr/templates/groups/edit.html
{% extends "base_site.html" %}

{% block title %}Groups - Edit{% endblock %}

{% block extrahead %}{{ block.super }}
  <script type="text/javascript" src="{{ SECR_STATIC_URL }}js/utils.js"></script>
{% endblock %}

{% block breadcrumbs %}{{ block.super }} 
  &raquo; <a href="../../">Groups</a>
  &raquo; <a href="../">{{ group.acronym }}</a>
  &raquo; Edit
{% endblock %}

{% block content %}

<div class="module group-container">
    <h2>Groups - Edit</h2>
    <form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
      <table id="groups-table" class="full-width amstable">
        <col width="150">
        {{ form }}
      </table>

  {% include "includes/awp_edit_form.html" %}

  {% include "includes/buttons_save_cancel.html" %}

    </form>
</div> <!-- module -->

{% endblock %}

ietf/secr/templates/groups/edit_gm.html
{% extends "base_site.html" %}

{% block title %}Groups - Edit{% endblock %}

{% block extrahead %}{{ block.super }}
  <script type="text/javascript" src="{{ SECR_STATIC_URL }}js/utils.js"></script>
  <script type="text/javascript" src="{{ SECR_STATIC_URL }}js/dynamic_inlines.js"></script>
{% endblock %}

{% block breadcrumbs %}{{ block.super }} 
  &raquo; <a href="../../../">Groups</a>
  &raquo; <a href="../../">{{ group.acronym }}</a>
  &raquo; <a href="../">Goals and Milestones</a>
  &raquo; Edit
{% endblock %}

{% block content %}

<div class="module group-container">
    <form id="edit-gm" enctype="multipart/form-data" action="" method="post">{% csrf_token %}

<div class="inline-group">
  <div class="tabular inline-related">
   <h2>Goals and Milestones</h2>
   {{ formset.management_form }}
   {{ formset.non_form_errors }}
   <table class="full-width">
     <thead><tr>
     {% for field in formset.forms.0.visible_fields %}
         <th>{{ field.label|capfirst }}</th>
     {% endfor %}
     </tr></thead>

     <tbody>
     {% for form in formset.forms %}
        {% if form.non_field_errors %}
        <tr><td colspan="3">{{ form.non_field_errors }}</td></tr>
        {% endif %}
        <tr class="{% cycle row1,row2 %}">

          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}
          {% for field in form.visible_fields %}
               <td>
                 {{ field.errors }}
                 {{ field }}
               </td>
          {% endfor %}
        </tr>
     {% endfor %}
     </tbody>
   </table>
</div> <!-- tabular inline-related -->
</div> <!-- inline-group -->

    {% include "includes/buttons_save_cancel.html" %}

    </form>
</div> <!-- module -->


{% endblock %}

ietf/secr/templates/groups/view.html
{% extends "base_site.html" %}

{% block title %}Groups - View{% endblock %}

{% block extrahead %}{{ block.super }}
  <script type="text/javascript" src="{{ SECR_STATIC_URL }}js/utils.js"></script>
{% endblock %}

{% block breadcrumbs %}{{ block.super }} 
  &raquo; <a href="../">Groups</a>
  &raquo; {{ group.acronym }}
{% endblock %}

{% block content %}

<div class="module group-container">
  <div id="groups-view-col1">
    <h2>Groups - View</h2>
      <table >
        <col width="150">
        <tr><td>Group Acronym:</td><td>{{ group.acronym }}</td></tr>
        <tr><td>Group Name:</td><td>{{ group.name }}</td></tr>
        <tr><td>Status:</td><td>{{ group.state }}</td></tr>
        <tr><td>Type:</td><td>{{ group.type }}</td></tr>
        <tr><td>Proposed Date:</td><td>{{ group.proposed_date|date:"Y-m-d" }}</td></tr>
        <tr><td>Start Date:</td><td>{{ group.start_date|date:"Y-m-d" }}</td></tr>
        <tr><td>Concluded Date:</td><td>{{ group.concluded_date|date:"Y-m-d" }}</td></tr>
        {% comment %}
        Here we need to check that group.area_director and group.area_director.area are defined before referencing.
        Otherwise the template would raise errors if the group area director record didn't exist or
        in the case of Area Director = TBD, the area field is NULL
        {% endcomment %}
        <tr><td>Primary Area:</td>
            <td>{% if not group.parent %}(No Data){% else %}
                  <a href="{% url "areas_view" name=group.parent.acronym %}">{{ group.parent }}</a>
                {% endif %}
            </td>
        </tr>
        <tr><td>Primary Area Director:</td>
            <td>{% if group.ad_role %}
                  <a href="{% url "rolodex_view" id=group.ad_role.person.id %}">{{ group.ad_role.person }}</a>
                {% endif %} 
            </td></tr>
        <tr><td>Meeting Scheduled:</td><td>{{ group.meeting_scheduled}}</td></tr>
        <tr><td>Email Address:</td><td>{{ group.list_email }}</td></tr>
        <tr><td>Email Subscription:</td><td>{{ group.list_subscribe }}</td></tr>
        <tr><td>Email Archive:</td><td>{{ group.list_archive }}</td></tr>
        {% if group.features.has_chartering_process %}
        <tr><td>Charter:</td><td><a href="{% url "groups_charter" acronym=group.acronym %}">View Charter</a></td></tr>
        {% else %}
        <tr><td>Description:</td><td>{{ group.description }}</td></tr>
        {% endif %}
        <tr><td>Comments:</td><td>{{ group.comments }}</td></tr>
        <tr><td>Last Modified Date:</td><td>{{ group.time }}</td></tr>
      </table>
      
      {% with group.groupurl_set.all as awps %}
          {% include "includes/awp_view.html" %}
      {% endwith %}

  </div> <!-- groups-view-col1 -->
  <div id="groups-view-col2">
      <div class="inline-related">
        <h2>Chairperson(s)</h2>
        <table>
        {% for role in group.chairs %}
          <tr><td><a href="{% url "rolodex_view" id=role.person.id %}">{{ role.person }}</a></td></tr>
        {% endfor %}
        </table>
      </div> <!-- inline-related -->

      <div class="inline-related">
        <h2>Document Editor(s)</h2>
        <table>
        {% for role in group.editors %}
          <tr><td><a href="{% url "rolodex_view" id=role.person.id %}">{{ role.person }}</a></td></tr>
        {% endfor %}
        </table>
      </div> <!-- inline-related -->

      <div class="inline-related">
        <h2>Technical Advisor(s)</h2>
        <table>
        {% for role in group.techadvisors %}
          <tr><td><a href="{% url "rolodex_view" id=role.person.id %}">{{ role.person }}</a></td></tr>
        {% endfor %}
        </table>
      </div> <!-- inline-related -->

      <div class="inline-related">
        <h2>Secretary(ies)</h2>
        <table>
        {% for role in group.secretaries %}
          <tr><td><a href="{% url "rolodex_view" id=role.person.id %}">{{ role.person }}</a></td></tr>
        {% endfor %}
        </table>
      </div> <!-- inline-related -->
      
    </div> <!-- groups-view-col2 -->

      <div class="button-group">
	<ul>
          <li><button onclick="window.location='edit/'">Edit</button></li>
          <li><button onclick="window.location='people/'">People</button></li>
          <li><button onclick="window.location='gm/'">G + M</button></li>
          {% comment %}
          <li><button onclick="window.location='{% url "sec.ids.views.search" id=group.group_acronym.acronym_id %}'">Drafts</button></li>
          <li><button onclick="window.location='{% url "sec.rfcs.views.search" id=group.group_acronym.acronym_id %}'">RFCs</button></li>
          {% endcomment %}
	</ul>
      </div> <!-- button-group -->
</div> <!-- module -->

{% endblock %}